# **FUNCTION USED ON ARRAY**



---

### 🧱 **Creation**
- `np.array()` – from list/tuple
- `np.zeros(shape)` – array of 0s
- `np.ones(shape)` – array of 1s
- `np.full(shape, value)` – filled with value
- `np.arange(start, stop, step)` – like `range()`
- `np.linspace(start, stop, num)` – evenly spaced numbers
- `np.random.rand(shape)` – random floats [0,1)
- `np.random.randint(low, high, size)` – random integers

---

### 🛠️ **Manipulation**
- `np.append(arr, values)` – adds values to end
- `np.insert(arr, index, values)` – inserts at index
- `np.delete(arr, index)` – removes elements
- `np.reshape(arr, new_shape)` – reshapes array
- `arr.flatten()` – converts to 1D
- `arr.ravel()` – flattens (faster, view)
- `arr.tolist()` – converts to Python list

---

### 🔍 **Information**
- `arr.shape` – dimensions
- `arr.ndim` – number of dimensions
- `arr.size` – total number of elements
- `arr.dtype` – data type of elements

---

### 🧮 **Math Operations**
- `np.sum(arr)` – sum of elements
- `np.mean(arr)` – average
- `np.median(arr)` – median
- `np.std(arr)` – standard deviation
- `np.min(arr)` / `np.max(arr)` – min/max
- `np.sort(arr)` – sorted array
- `np.unique(arr)` – unique values

---

### 🔢 **Element-wise Operations**
- `arr + 2`, `arr * 2` – scalar math
- `arr1 + arr2` – element-wise addition
- `np.sqrt(arr)` – square root
- `np.exp(arr)` – exponential
- `np.log(arr)` – natural log

---

### 🔁 **Comparison / Boolean**
- `arr > 5`, `arr == 10` – element-wise comparison
- `np.where(condition, x, y)` – conditionally choose values

---


In [31]:
# CREATION OF ARRAY..
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [32]:
import numpy as np
ARR = np.array([1,2,3,4,5,6,7,8,9,10])

In [33]:
# APPEND FUNCTION:
ARR=np.append(ARR,11)
ARR

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
# EXTEND FUNCTION: EXTEND ONLY WORKS FOR LIST....
ARR = np.append(ARR,[12,13])
ARR

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [35]:
# INSERT FUNCTION:np.insert(ARR,INDEX,VALUE)
ARR=np.insert(ARR,len(ARR),14)
ARR

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
# DELETE FUNCTION:
ARR=np.delete(ARR,len(ARR)-1)
ARR

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [37]:
# FLATTEN FUNCTION: CONVERT INTO 1 D
ARR2=ARR.flatten()
ARR2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [38]:
ARR.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [39]:
ARR.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [41]:
ARR.shape

(13,)

In [42]:
ARR.ndim

1

In [43]:
ARR.size

13

In [46]:
ARR.dtype

dtype('int32')

In [47]:
np.mean(ARR)

7.0

In [48]:
np.sum(ARR)

91

In [49]:
np.min(ARR)

1

In [50]:
np.max(ARR)

13

In [51]:
np.median(ARR)

7.0

In [52]:
np.std(ARR)

3.7416573867739413

In [53]:
np.sort(ARR)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [54]:
np.unique(ARR)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])